//#include <stddef.h>
//#include "AllHeaders.h"

// template class opendnp3::Opendnp3Gadget<int>;
// template class opendnp3::Opendnp3Gadget<unsigned int>;
// template class opendnp3::Opendnp3Gadget<float>;
// template class opendnp3::Opendnp3Gadget<bool>;
#ifndef PYOD3_ALLHEADERS_H
#define PYOD3_ALLHEADERS_H
#define ASIO_STANDALONE

#include <stddef.h>

// ---------- OPENDNP3 HEADERS ----------

// -- root
#include "deps/opendnp3/cpp/lib/include/opendnp3/ConsoleLogger.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/DNP3Manager.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/ErrorCodes.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/IResource.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/IStack.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/StackStatistics.h"

// -- app
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/parsing/ICollection.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/AnalogCommandEvent.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/AnalogOutput.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/AppConstants.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/BaseMeasurementTypes.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/BinaryCommandEvent.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/ClassField.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/ControlRelayOutputBlock.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/DNPTime.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/EventCells.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/EventTriggers.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/EventType.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/Flags.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/GroupVariationID.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/Indexed.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/IINField.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/MeasurementInfo.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/MeasurementTypes.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/OctetData.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/app/OctetString.h"

// -- Channel
#include "deps/opendnp3/cpp/lib/include/opendnp3/channel/ChannelRetry.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/channel/IChannel.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/channel/IChannelListener.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/channel/IListener.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/channel/IOpenDelayStrategy.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/channel/IPEndpoint.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/channel/PrintingChannelListener.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/channel/SerialSettings.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/channel/TLSConfig.h"
// -- Decoder
#include "deps/opendnp3/cpp/lib/include/opendnp3/decoder/Decoder.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/decoder/IDecoderCallbacks.h"

// -- Gen
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/AnalogOutputStatusQuality.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/AnalogQuality.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/AssignClassType.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/Attributes.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/BinaryOutputStatusQuality.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/BinaryQuality.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/ChannelState.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/CommandPointState.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/CommandStatus.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/CounterQuality.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/DoubleBitBinaryQuality.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/DoubleBit.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/EventAnalogOutputStatusVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/EventAnalogVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/EventBinaryOutputStatusVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/EventBinaryVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/EventCounterVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/EventDoubleBinaryVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/EventFrozenCounterVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/EventMode.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/EventOctetStringVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/EventSecurityStatVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/FlagsType.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/FlowControl.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/FrozenCounterQuality.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/FunctionCode.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/GroupVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/IndexQualifierMode.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/IntervalUnits.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/LinkFunction.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/LinkStatus.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/MasterTaskType.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/OperateType.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/OperationType.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/Parity.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/PointClass.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/QualifierCode.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/RestartMode.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/RestartType.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/ServerAcceptMode.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/StaticAnalogOutputStatusVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/StaticAnalogVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/StaticBinaryOutputStatusVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/StaticBinaryVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/StaticCounterVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/StaticDoubleBinaryVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/StaticFrozenCounterVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/StaticOctetStringVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/StaticSecurityStatVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/StaticTimeAndIntervalVariation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/StaticTypeBitmask.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/StopBits.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/TaskCompletion.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/TimestampQuality.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/TimeSyncMode.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/gen/TripCloseCode.h"

// -- link
#include "deps/opendnp3/cpp/lib/include/opendnp3/link/Addresses.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/link/ILinkListener.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/link/LinkConfig.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/link/LinkHeaderFields.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/link/LinkStatistics.h"

// -- logging
#include "deps/opendnp3/cpp/lib/include/opendnp3/logging/ILogHandler.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/logging/Logger.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/logging/LogLevels.h"

// -- master
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/CommandPointResult.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/CommandResultCallbackT.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/CommandSet.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/DefaultListenCallbacks.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/DefaultMasterApplication.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/HeaderInfo.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/HeaderTypes.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/ICommandCollection.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/ICommandProcessor.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/ICommandTaskResult.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/IListenCallbacks.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/IMasterApplication.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/IMaster.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/IMasterOperations.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/IMasterScan.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/IMasterSession.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/ISessionAcceptor.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/ISOEHandler.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/ITaskCallback.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/IUTCTimeSource.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/MasterParams.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/MasterStackConfig.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/PrintingCommandResultCallback.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/PrintingSOEHandler.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/ResponseInfo.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/RestartOperationResult.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/TaskConfig.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/TaskId.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/TaskInfo.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/master/X509Info.h"

// -- outstation
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/ApplicationIIN.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/DatabaseConfig.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/DefaultOutstationApplication.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/EventBufferConfig.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/ICommandHandler.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/IDnpTimeSource.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/IOutstationApplication.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/IOutstation.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/IUpdateHandler.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/MeasurementConfig.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/NumRetries.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/OutstationConfig.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/OutstationParams.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/OutstationStackConfig.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/SimpleCommandHandler.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/StaticTypeBitfield.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/UpdateBuilder.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/outstation/Updates.h"

// -- util
#include "deps/opendnp3/cpp/lib/include/opendnp3/util/Buffer.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/util/StaticOnly.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/util/TimeDuration.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/util/Timestamp.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/util/Uncopyable.h"
#include "deps/opendnp3/cpp/lib/include/opendnp3/util/UTCTimestamp.h"

#endif